name: weekycal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.0
  shared_preferences: ^2.0.8
  home_widget:
  timezone: ^0.9.4
  permission_handler: ^11.4.0
  flutter_local_notifications: ^18.0.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
